version: 2

jobs:
  build:
    docker:
      - image: circleci/elixir:latest
      - image: postgres:9.6.5
        environment:
          POSTGRES_USER: postgres
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - dependency-cache-{{.Branch}}-{{checksum "mix.lock"}}
            - dependency-cache-{{.Branch}}
            - dependency-cache-
      - run: mix deps.get
      - save_cache:
          key: dependency-cache-{{.Branch}}-{{checksum "mix.lock"}}
          paths:
            - deps
      - run: mix compile
      - run: MIX_ENV=test mix compile
      - run: MIX_ENV=prod mix compile
      - save_cache:
          key: dependency-cache-{{.Branch}}-{{checksum "mix.lock"}}
          paths:
            - _build
      - run: MIX_ENV=test mix ecto.create
      - run: MIX_ENV=test mix ecto.migrate
      # - run: mix format --check-formatted
      - run: mix coveralls.circle

workflows:
  version: 2
  build_test:
    jobs:
      - build
